// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");
var Canvas2dRe = require("bs-webapi/src/canvas/Canvas2dRe.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Frogger_spritesPng = require("../assets/frogger_sprites.png");

var img = new Image();

img.src = Frogger_spritesPng;

var startWorld = /* record */[
  /* frog : record */[
    /* x */0,
    /* y */0,
    /* width */35,
    /* height */30,
    /* frames */2,
    /* frameIndex */0,
    /* frameSpeed */4
  ],
  /* width */760,
  /* height */600
];

function drawSprite(ctx, sprite) {
  var frogFrame = Caml_int32.mod_(sprite[/* frameIndex */5] / 1000 | 0, sprite[/* frames */4]);
  var startX = frogFrame * sprite[/* width */2];
  ctx.drawImage(img, startX, 370, sprite[/* width */2], sprite[/* height */3], 0, 300, sprite[/* width */2], sprite[/* height */3]);
  return /* () */0;
}

function render(ctx, world) {
  Canvas2dRe.setFillStyle(ctx, /* String */0, "black");
  ctx.fillRect(0, 0, world[/* width */1], world[/* height */2]);
  return drawSprite(ctx, world[/* frog */0]);
}

var lastTime = [Date.now()];

function update(ctx, world) {
  var now = Date.now();
  var dt = now - lastTime[0];
  render(ctx, world);
  lastTime[0] = Date.now();
  var init = world[/* frog */0];
  var newWorld_000 = /* frog : record */[
    /* x */init[/* x */0],
    /* y */init[/* y */1],
    /* width */init[/* width */2],
    /* height */init[/* height */3],
    /* frames */init[/* frames */4],
    /* frameIndex */world[/* frog */0][/* frameIndex */5] + dt * world[/* frog */0][/* frameSpeed */6],
    /* frameSpeed */init[/* frameSpeed */6]
  ];
  var newWorld_001 = /* width */world[/* width */1];
  var newWorld_002 = /* height */world[/* height */2];
  var newWorld = /* record */[
    newWorld_000,
    newWorld_001,
    newWorld_002
  ];
  requestAnimationFrame((function () {
          return update(ctx, newWorld);
        }));
  return /* () */0;
}

function load() {
  var match = document.getElementById("canvas");
  var canvas = (match == null) ? (console.log("cant find canvas canvas \n"), Pervasives.failwith("fail")) : match;
  canvas.setAttribute("height", String(600) + "px");
  canvas.setAttribute("width", String(760) + "px");
  var context = canvas.getContext("2d");
  return update(context, startWorld);
}

window.onload = load;

exports.img = img;
exports.startWorld = startWorld;
exports.drawSprite = drawSprite;
exports.render = render;
exports.lastTime = lastTime;
exports.update = update;
exports.load = load;
/* img Not a pure module */
